version: '3.7'

services:
  api:
    container_name: safeboda-api
    build:
      context: .
      target: production
    ports:
      - ${SERVER_PORT}:3000
    command: npm run start:prod
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - db
      - test-db
  db:
    container_name: safeboda-db
    image: postgres:14-alpine
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  test-db:
    container_name: safeboda-test-db
    image: postgres:14-alpine
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_USER: ${TEST_DB_USERNAME}
      POSTGRES_DB: ${TEST_DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${TEST_DB_PORT}:5432
    volumes:
      - testpgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
  testpgdata:
